### PR TITLE
Added Linked List Problem in Linked List Folder

### PR DESCRIPTION
**Pull request by Sourz-101**
Please accept my PR and label it "hacktoberfest-accepted" so it can be counted on hacktoberfest website
Thanks for giving me this opportunity

### CODE REVIEW

**Comment by nishantkumar1308** [comment]
@Sourz-101 Bro add some more problems as this is intial repo.

**Comment by Sourz-101** [comment]
ok sure

**Comment by Sourz-101** [comment]
@nishantkumar1308 hey
I have uploaded 7 questions to the Linked List folder
Please merge them and label them as hacktober-accepted so they can be counted in hacktoberfest
Thank You

**Comment by nishantkumar1308** [comment]
@Sourz-101 there is conflict in merging files by your side because your branch is not upto date, you have to revert the commit and push again.

**Pull request closed without merging**
